### ISSUE TITLE
Automatic Hue Bridge Detection

### ISSUE THREAD

**Issue by hongkongkiwi** [markbergsma/pimatic-hue-zll#11]
Hi, 

You might consider changing the backend to use this module:
https://github.com/peter-murray/node-hue-api

It handles bridge discovery and automatic API key retrieving.

**Comment by sweebee** [comment]
This plug-in already uses it. https://github.com/markbergsma/pimatic-hue-zll/blob/master/package.json#L28

**Comment by markbergsma** [comment]
Yes indeed; the plugin already uses node-hue-api, and that's not the reason/blocker for missing bridge detection. Pimatic 0.8 makes that near-impossible, but Pimatic 0.9 (to be released soon) supports autodiscovery, so it will be added soon.

**Comment by markbergsma** [comment]
I've just published v0.3.0 on npm, which supports bridge auto-discovery, as well as discovery of lights and light groups in Pimatic 0.9.
