### ISSUE TITLE
control unreachable lights

### ISSUE THREAD

**Issue by sweebee** [markbergsma/pimatic-hue-zll#12]
Somehow I have 2 switches (Osram plug). That shows unreachable. I can control them in the hue app while they are unreachable. This plugin disables the device completely. Would be nice to control them even when they are disabled. And show the unreachable state in a different way on the device without disabling the switch.

So I have 3 Osram plugs from which 2 shows unreachable. Can't find out why but they work fine.

**Comment by ToniTornado** [comment]
I updated the firmware of some bulbs via osram lightify bridge and re-paired them to hue bridge. Now most of them are shown as reachable=false

**Comment by thexperiments** [comment]
Lately my lights work fine but it should be quite easy to add some override to the settings to ignore the state and try to switch anyway
