### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by quintz** [markbergsma/pimatic-hue-zll#8]
Hi Mark,

I encountered a issue while I was setting up pimatic freshly.

I installed the plugin via the Web Gui, put my old settings in the config and at the boot up I get this issue:
`20:35:48.594 [pimatic] error: Invalid config of pimatic-hue-zll: Property "name" is not a valid property`

I didn't put the "name" property there, it did this by it self.
Did I miss something or what is happening? : - P

Cheers

**Comment by Jorijn** [comment]
+1 having the same problem

**Comment by mwittig** [comment]
Note, device config properties created at runtime must be added to the device config schema.
